global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'catalogue'
    static_configs:
      - targets: ['catalogue:8000']
    metrics_path: '/metrics'

  - job_name: 'panier'
    static_configs:
      - targets: ['panier:8001']
    metrics_path: '/metrics'

  - job_name: 'paiement'
    static_configs:
      - targets: ['paiement:8002']
    metrics_path: '/metrics'
